#!/usr/bin/env python3
from pathlib import Path
import json,subprocess,sys,tempfile
HERE=Path(__file__).resolve().parent;MOD=HERE.parent;V=MOD.parent;checks=[]
def chk(n,ok,d=''):checks.append((n,bool(ok),str(d)))
def run(args):
 q=subprocess.run([sys.executable,*map(str,args)],capture_output=True,text=True);return q.returncode,q.stdout+q.stderr
m=json.loads((V/'CURRENT_PRODUCTION_MANIFEST.json').read_text())
chk('stack_v19_or_v20',m.get('current_stack') in {'V19.0.0','V20.0.0'},m.get('current_stack'))
chk('fundamental_only',m.get('decision_authority',{}).get('direction')=='FUNDAMENTAL_ONLY',m.get('decision_authority'))
chk('module101_authority',m.get('canonical_authorities',{}).get('d3_unified_edge')=='101 Unified Causal Fuzzy Edge Integration and Permission Adjudication Engine/00 Unified Causal Fuzzy Edge Integration and Permission Adjudication Engine MOC.md',m.get('canonical_authorities'))
d3=m.get('d3_unified_edge') or {};chk('d3_mode',d3.get('authority_mode')=='ENFORCED_CAUSAL_MODULATION',d3);chk('no_flip',d3.get('direction_flip_allowed') is False,d3);chk('no_new_perm',d3.get('new_permission_from_pre_d3_no_trade_v19') is False,d3)
d2=m.get('d2_market_sciences') or {};chk('d2_still_shadow_source',d2.get('authority_mode')=='CANONICAL_SHADOW',d2);chk('d2_direct_none',d2.get('direct_permission_effect')=='NONE',d2);chk('d2_promoted_only_via_101',d2.get('d3_promotion_state')=='PROMOTED_VIA_MODULE_101_ONLY',d2)
pol=json.loads((MOD/'config/d3_integration_policy.json').read_text());chk('no_voting',pol['science_voting_forbidden'] and pol['additive_score_forbidden'],pol);chk('same_root',pol['rules']['same_root_dedup_required'],pol);chk('funding_no_generic_sign',pol['rules']['funding_no_universal_sign'],pol)
rc,o=run([HERE/'alphalab_d3_coverage_audit.py','--vault-root',V]);z=json.loads(o);chk('six_market_translation',rc==0 and z.get('markets')==6 and z.get('integration_books')==6,o)
with tempfile.TemporaryDirectory() as td0:
 td=Path(td0); inp=td/'in.json';out=td/'out.json'
 base={'version':'1.0.0','instrument':'NASDAQ100','analysis_cutoff_utc':'2026-08-08T00:00:00Z','fundamental_direction':'BULLISH','pre_d3_research_edge':'EDGE_ACTIVE','pre_d3_permission':'BUY','integration_vectors':[],'capacity_sufficient_for_intended_execution':True,'capacity_scope_matched':True}
 inp.write_text(json.dumps(base));rc,o=run([HERE/'alphalab_d3_integrate.py','--input',inp,'--output',out]);z=json.loads(out.read_text());chk('active_maintained',rc==0 and z['final_permission']=='BUY' and z['final_direction']=='BULLISH',o)
 x=dict(base);x['pre_d3_permission']='NO_TRADE';x['pre_d3_research_edge']='EDGE_CONDITIONAL';x['integration_vectors']=[{'science':'ACTUAL_FLOW','causal_channel':'IDENTIFIED_BUYING','alignment_to_fundamental':'SUPPORTIVE','obstruction_class':'SUPPORT','materiality':'MATERIAL','evidence_grade':'DIRECT_IDENTIFIED','root_id':'R1'}];inp.write_text(json.dumps(x));run([HERE/'alphalab_d3_integrate.py','--input',inp,'--output',out]);z=json.loads(out.read_text());chk('support_cannot_create_permission',z['final_permission']=='NO_TRADE' and z['promotion_readiness'] in {'MEDIUM','HIGH'},z)
 x=dict(base);x['integration_vectors']=[{'science':'ACTUAL_FLOW','causal_channel':'SELLING','alignment_to_fundamental':'OPPOSING','obstruction_class':'TRANSMISSION_BREAK','materiality':'MATERIAL','evidence_grade':'DIRECT_IDENTIFIED','root_id':'FLOW1','persistence':'PERSISTENT'}];inp.write_text(json.dumps(x));run([HERE/'alphalab_d3_integrate.py','--input',inp,'--output',out]);z=json.loads(out.read_text());chk('flow_break_suppresses_not_flips',z['final_permission']=='NO_TRADE' and z['final_direction']=='BULLISH' and z['d3_edge_quality']=='SUPPRESSED',z)
 x=dict(base);x['integration_vectors']=[{'science':'INSTITUTIONAL_MECHANICS','causal_channel':'CLOSE_AUCTION','alignment_to_fundamental':'NON_DIRECTIONAL','obstruction_class':'DELAY','materiality':'DECISION_CRITICAL','evidence_grade':'OFFICIAL_OR_EXCHANGE','root_id':'M1'}];inp.write_text(json.dumps(x));run([HERE/'alphalab_d3_integrate.py','--input',inp,'--output',out]);z=json.loads(out.read_text());chk('mechanics_delay',z['final_permission']=='NO_TRADE' and z['d3_edge_quality']=='DELAYED' and z['validity_action']=='UNTIL_MECHANICAL_EVENT',z)
 x=dict(base);x['capacity_sufficient_for_intended_execution']=False;inp.write_text(json.dumps(x));run([HERE/'alphalab_d3_integrate.py','--input',inp,'--output',out]);z=json.loads(out.read_text());chk('capacity_block',z['final_permission']=='NO_TRADE' and z['d3_edge_quality']=='CAPACITY_BLOCKED',z)
 x=dict(base);x['integration_vectors']=[{'science':'POSITIONING_OWNERSHIP','causal_channel':'CROWDING','alignment_to_fundamental':'NON_DIRECTIONAL','obstruction_class':'FRICTION','materiality':'MATERIAL','evidence_grade':'OFFICIAL_OR_EXCHANGE','root_id':'P1','crowding_state':'VERY_CROWDED','fragility_state':'EXTREME'}];inp.write_text(json.dumps(x));run([HERE/'alphalab_d3_integrate.py','--input',inp,'--output',out]);z=json.loads(out.read_text());chk('crowding_fragility_not_sell',z['final_permission']=='BUY' and z['final_direction']=='BULLISH' and 'CROWDING_FRAGILITY' in z['confidence_caps'],z)
 x=dict(base);x['integration_vectors']=[{'science':'ACTUAL_FLOW','causal_channel':'A','alignment_to_fundamental':'SUPPORTIVE','obstruction_class':'SUPPORT','materiality':'MATERIAL','evidence_grade':'DIRECT_IDENTIFIED','root_id':'SAME'},{'science':'FUNDING_PLUMBING','causal_channel':'B','alignment_to_fundamental':'SUPPORTIVE','obstruction_class':'SUPPORT','materiality':'MATERIAL','evidence_grade':'OFFICIAL_OR_EXCHANGE','root_id':'SAME'}];inp.write_text(json.dumps(x));run([HERE/'alphalab_d3_integrate.py','--input',inp,'--output',out]);z=json.loads(out.read_text());chk('same_root_dedup',z['deduplicated_root_count']==1 and z['d3_edge_quality'] in {'CONFIRMED','MAINTAINED'},z)
 x=dict(base);x['integration_vectors']=[{'science':'ACTUAL_FLOW','causal_channel':'A','alignment_to_fundamental':'SUPPORTIVE','obstruction_class':'SUPPORT','materiality':'MATERIAL','evidence_grade':'DIRECT_IDENTIFIED','root_id':'R1'},{'science':'FUNDING_PLUMBING','causal_channel':'B','alignment_to_fundamental':'SUPPORTIVE','obstruction_class':'SUPPORT','materiality':'MATERIAL','evidence_grade':'OFFICIAL_OR_EXCHANGE','root_id':'R2'}];inp.write_text(json.dumps(x));run([HERE/'alphalab_d3_integrate.py','--input',inp,'--output',out]);z=json.loads(out.read_text());chk('two_independent_support_amplifies_existing',z['final_permission']=='BUY' and z['d3_edge_quality']=='AMPLIFIED',z)
 rc,o=run([HERE/'alphalab_d3_validate.py','--input',out]);chk('output_validator',rc==0,o)
# Regression and deployment preflights are executed by VERIFY_PATCH.py, not recursively inside this focused D3 unit self-test.
passed=sum(ok for _,ok,_ in checks);failed=[{'name':n,'detail':d[-1800:]} for n,ok,d in checks if not ok]
print(json.dumps({'status':'PASS' if not failed else 'FAIL','passed':passed,'total':len(checks),'failed':failed},indent=2));sys.exit(0 if not failed else 2)
