#!/usr/bin/env python3
from pathlib import Path
import json,subprocess,sys,tempfile
HERE=Path(__file__).resolve().parent;MOD=HERE.parent;V=MOD.parent;checks=[]
def chk(n,ok,d=''):checks.append((n,bool(ok),str(d)))
def run(args):
 q=subprocess.run([sys.executable,*map(str,args)],capture_output=True,text=True);return q.returncode,q.stdout+q.stderr
m=json.loads((V/'CURRENT_PRODUCTION_MANIFEST.json').read_text())
chk('stack_v19_to_v21',m.get('current_stack') in {'V19.0.0','V20.0.0','V21.0.0','V21.1.0','V21.2.0','V21.3.0'},m.get('current_stack'))
chk('fundamental_only',m.get('decision_authority',{}).get('direction')=='FUNDAMENTAL_ONLY',m.get('decision_authority'))
d3=m.get('d3_unified_edge') or {};chk('d3_mode',d3.get('authority_mode')=='ENFORCED_CAUSAL_MODULATION',d3);chk('no_flip',d3.get('direction_flip_allowed') is False,d3)
pol=json.loads((MOD/'config/d3_integration_policy.json').read_text());chk('policy_1_1',pol.get('version')=='1.1.0',pol);chk('no_voting',pol['science_voting_forbidden'] and pol['additive_score_forbidden'],pol);chk('multi_channel_root',pol['rules'].get('same_root_channels_must_be_preserved') is True,pol)
with tempfile.TemporaryDirectory() as td0:
 td=Path(td0);inp=td/'in.json';out=td/'out.json'
 base={'version':'1.1.0','instrument':'NASDAQ100','analysis_cutoff_utc':'2026-08-08T00:00:00Z','fundamental_direction':'BULLISH','pre_d3_research_edge':'EDGE_ACTIVE','pre_d3_permission':'BUY','integration_vectors':[],'capacity_sufficient_for_intended_execution':True,'capacity_scope_matched':True}
 inp.write_text(json.dumps(base));rc,o=run([HERE/'alphalab_d3_integrate.py','--input',inp,'--output',out]);z=json.loads(out.read_text());chk('active_maintained',rc==0 and z['final_permission']=='BUY' and z['version']=='1.1.0',z)
 x=dict(base);x['pre_d3_permission']='NO_TRADE';x['pre_d3_research_edge']='EDGE_CONDITIONAL';x['integration_vectors']=[{'science':'ACTUAL_FLOW','causal_channel':'IDENTIFIED_BUYING','alignment_to_fundamental':'SUPPORTIVE','obstruction_class':'SUPPORT','materiality':'MATERIAL','evidence_grade':'DIRECT_IDENTIFIED','root_id':'R1'}];inp.write_text(json.dumps(x));run([HERE/'alphalab_d3_integrate.py','--input',inp,'--output',out]);z=json.loads(out.read_text());chk('support_cannot_create_permission',z['final_permission']=='NO_TRADE',z)
 x=dict(base);x['integration_vectors']=[{'science':'ACTUAL_FLOW','causal_channel':'RATES_SUPPORT','alignment_to_fundamental':'SUPPORTIVE','obstruction_class':'SUPPORT','materiality':'MATERIAL','evidence_grade':'DIRECT_IDENTIFIED','root_id':'SAME'},{'science':'FUNDING_PLUMBING','causal_channel':'GROWTH_STRESS','alignment_to_fundamental':'OPPOSING','obstruction_class':'FRICTION','materiality':'MATERIAL','evidence_grade':'OFFICIAL_OR_EXCHANGE','root_id':'SAME'}];inp.write_text(json.dumps(x));run([HERE/'alphalab_d3_integrate.py','--input',inp,'--output',out]);z=json.loads(out.read_text());rm=z['root_channel_map'][0];chk('same_root_multi_channel_preserved',z['deduplicated_root_count']==1 and len(rm['channels'])==2 and rm['net_root_state']=='CONTESTED' and 'SAME' in z['contested_root_ids'],z)
 x=dict(base);x['integration_vectors']=[{'science':'ACTUAL_FLOW','causal_channel':'SELLING','alignment_to_fundamental':'OPPOSING','obstruction_class':'TRANSMISSION_BREAK','materiality':'MATERIAL','evidence_grade':'DIRECT_IDENTIFIED','root_id':'FLOW1','persistence':'PERSISTENT'}];inp.write_text(json.dumps(x));run([HERE/'alphalab_d3_integrate.py','--input',inp,'--output',out]);z=json.loads(out.read_text());chk('flow_break_suppresses_not_flips',z['final_permission']=='NO_TRADE' and z['final_direction']=='BULLISH',z)
 x=dict(base);x['integration_vectors']=[{'science':'ACTUAL_FLOW','causal_channel':'A','alignment_to_fundamental':'SUPPORTIVE','obstruction_class':'SUPPORT','materiality':'MATERIAL','evidence_grade':'DIRECT_IDENTIFIED','root_id':'R1'},{'science':'FUNDING_PLUMBING','causal_channel':'B','alignment_to_fundamental':'SUPPORTIVE','obstruction_class':'SUPPORT','materiality':'MATERIAL','evidence_grade':'OFFICIAL_OR_EXCHANGE','root_id':'R2'}];inp.write_text(json.dumps(x));run([HERE/'alphalab_d3_integrate.py','--input',inp,'--output',out]);z=json.loads(out.read_text());chk('two_independent_support',z['support_independent_root_count']==2 and z['d3_edge_quality']=='AMPLIFIED',z)
 x=dict(base);x['cognitive_context']={'cognitive_state':'CONTESTED'};inp.write_text(json.dumps(x));run([HERE/'alphalab_d3_integrate.py','--input',inp,'--output',out]);z=json.loads(out.read_text());chk('cognitive_fail_closed',z['final_permission']=='NO_TRADE' and z['cognitive_context_received'],z)
passed=sum(ok for _,ok,_ in checks);failed=[{'name':n,'detail':d[-1800:]} for n,ok,d in checks if not ok]
print(json.dumps({'status':'PASS' if not failed else 'FAIL','passed':passed,'total':len(checks),'failed':failed},indent=2));sys.exit(0 if not failed else 2)
