from __future__ import annotations
from .common import PHASE,NEXT,REPO,load,git_commit
from .freeze import verify_manifest
from .gates import collect,certification_state,real_p09,real_r01

def status():
 rel=load(PHASE/'release/ALPHA_DESK_V3_FINAL_RELEASE_MANIFEST.json',{}) or {};cert=load(PHASE/'certification/FINAL_CERTIFICATION_RECEIPT.json',{}) or {};fr=verify_manifest(REPO);p09=real_p09();q=real_r01();g,_=collect(False,False,REPO)
 from AD_V3_PHASE_04_CONTROL_ROOM_TRUE_FORWARD_COMMISSIONING.runtime.promotion import load_state
 ps=load_state(NEXT/'AD_V3_PHASE_04_CONTROL_ROOM_TRUE_FORWARD_COMMISSIONING')
 return {'record_type':'AD_V3_P12_STATUS','implementation_status':cert.get('implementation_status','UNKNOWN'),'version':'3.12.3-v31-r03-perspective','release_candidate':rel.get('release_candidate'),'release_fingerprint':rel.get('release_fingerprint'),'git_commit':git_commit(),'certification_state':certification_state(),'science_freeze':fr.get('classes',{}).get('SCIENTIFIC_IMMUTABLE',{}).get('status'),'runtime_freeze':fr.get('classes',{}).get('RUNTIME_IMMUTABLE',{}).get('status'),'report_freeze':fr.get('classes',{}).get('REPORT_CONTRACT_IMMUTABLE',{}).get('status'),'certification_freeze':fr.get('classes',{}).get('CERTIFICATION_IMMUTABLE',{}).get('status'),'golden_certification':(load(PHASE/'certification/GOLDEN_CERTIFICATION_RECEIPT.json',{}) or {}).get('status'),'rollback_certification':(load(PHASE/'certification/ROLLBACK_CERTIFICATION_RECEIPT.json',{}) or {}).get('status'),'p09_forward_state':(p09.get('statistics') or {}).get('forward_evidence_state'),'p09_mature_episodes':(p09.get('statistics') or {}).get('mature_episode_count'),'r01_forward_quality_state':q.get('forward_quality_state'),'r01_coverage_state':q.get('coverage_state'),'r01_critical_subgroup_state':q.get('critical_subgroup_state'),'r01_production_qualification':q.get('production_qualification_state'),'promotion_eligibility':all(v for k,v in g.items() if k!='EXPLICIT_OPERATOR_APPROVAL'),'gate_results':g,'production_authority':ps.get('state','SHADOW_COMMISSIONING'),'V3_state':ps.get('state','SHADOW_COMMISSIONING'),'trade_execution_authority':'NONE'}
