#!/usr/bin/env python3
from pathlib import Path
import json,subprocess,sys,tempfile,copy,hashlib
R=Path(__file__).resolve().parents[2];M=R/'103 Cognitive Multi-Hypothesis Scenario and Adversarial Intelligence Engine';T=M/'tools';checks=[]
def ck(n,c,d=None):checks.append({'name':n,'pass':bool(c),'detail':d})
def run(args):
 q=subprocess.run([sys.executable,*map(str,args)],capture_output=True,text=True);return q.returncode,q.stdout,q.stderr
def tr(i,desc,mat='MATERIAL',mode='MANUAL_OBSERVATION'):
 z={'trigger_id':i,'description':desc,'monitor_mode':mode,'materiality':mat,'state_change_hazard':'MODERATE'}
 if mode=='MANUAL_OBSERVATION':z['manual_observation']=desc
 if mode=='MACHINE_PREDICATE':z.update({'metric':'US2Y','operator':'CROSSES_ABOVE','reference':'EVENT_LEVEL'})
 if mode=='EVENT_RELEASE':z.update({'event_id':i+'_EVENT'})
 return z
def ev(i,role='SUPPORT',mat='MATERIAL',h='SESSION_1_6H',root=None):
 return {'evidence_id':i,'evidence_type':'FACT_REF','fact_id':'FACT_'+i,'root_id':root or 'ROOT_'+i,'role':role,'materiality':mat,'horizon':h,'description':i,'source_grade':'OFFICIAL_PRIMARY','lineage_status':'TRACEABLE','resolution_state':'NOT_CHECKED','resolved_fact_sha256':None}
def hyp(i,pl='DOMINANT',direction='BULLISH'):
 return {'hypothesis_id':i,'title':i,'family':'GROWTH','mechanism':'growth fact to rates and earnings transmission','root_ids':['ROOT_'+i+'S'],'target_horizons':['SESSION_1_6H'],'direction_by_horizon':{'SESSION_1_6H':direction},'supporting_evidence':[ev(i+'S',root='ROOT_'+i+'S')],'contradicting_evidence':[],'missing_evidence':[{'evidence_id':i+'M','evidence_type':'MISSING_EVIDENCE','fact_id':None,'lineage_ref':None,'root_id':None,'role':'MISSING','materiality':'SUPPORTING','horizon':'SESSION_1_6H','description':'watch','source_grade':None,'lineage_status':'UNAVAILABLE','resolution_state':'NOT_CHECKED','resolved_fact_sha256':None}],'expected_leaders':[{'name':'US2Y','relationship':'INDEPENDENT'}],'expected_market_signatures':['rates lead'],'confirmation_triggers':[tr(i+'C','US2Y confirms')],'invalidation_triggers':[tr(i+'I','US2Y reverses')],'regime_dependencies':['GROWTH_STABLE'],'reflexive_loops':[],'plausibility_band':pl,'evidence_quality':'HIGH','causal_coherence':'HIGH','materiality':'MATERIAL','outside_fundamental_strategy':False}
def scen(i,role,hid,direction,pl):
 other='S2' if i=='S1' else 'S1';return {'scenario_id':i,'role':role,'source_hypothesis_ids':[hid],'plausibility_band':pl,'horizon':'SESSION_1_6H','direction':direction,'required_conditions':['condition'],'early_indicators':['leader'],'confirmation_triggers':[tr(i+'C','confirm')],'invalidation_triggers':[tr(i+'I','invalidate')],'expected_leaders':[{'name':'US2Y','relationship':'INDEPENDENT'}],'expected_market_signature':['signature'],'permission_implication':'SUPPORT_EXISTING' if direction=='BULLISH' else 'CONSTRAIN_EXISTING','transition_paths':[{'to_scenario_id':other,'trigger':tr(i+'T','transition')}], 'calibrated_probability':None}
def base():
 h1=hyp('H1');h2=hyp('H2','COMPETITIVE','BEARISH')
 return {'version':'1.2.0','instrument':'NASDAQ100','analysis_cutoff_utc':'2026-08-08T12:00:00Z','active_strategy_horizon':'SESSION_1_6H','fundamental_direction':'BULLISH','pre_cognitive_permission':'BUY',
 'cognitive_applicability':{'surprise_state':{'status':'NOT_APPLICABLE','reason':'no material scheduled event'},'policy_reaction_state':{'status':'NOT_APPLICABLE','reason':'growth-led test, not policy-led'},'regime_state':{'status':'PRESENT','reason':'directional run requires regime context'},'causal_graph':{'status':'PRESENT','reason':'directional run requires causal map'},'reflexivity_state':{'status':'NOT_APPLICABLE','reason':'no reflexive loop asserted'},'consumption_state':{'status':'PRESENT','reason':'actionable permission requires remaining asymmetry'},'driver_transition':{'status':'NOT_APPLICABLE','reason':'first observation; no prior driver state'},'global_reconciliation':{'status':'NOT_APPLICABLE','reason':'single-market unit test'}},
 'hypothesis_set':{'version':'1.2.0','instrument':'NASDAQ100','analysis_cutoff_utc':'2026-08-08T12:00:00Z','active_horizon':'SESSION_1_6H','hypotheses':[h1,h2],'tournament_state':'DOMINANT','dominant_hypothesis_ids':['H1'],'strongest_challenger_ids':['H2'],'single_hypothesis_justification':None,'decision_critical_conflicts':[],'resolution_observations':[tr('RES','US2Y path')],'tournament_basis':{'independent_root_count':2,'critical_contradiction_count':0,'signature_alignment':'STRONG','regime_consistency':'PASS','falsifiability':'HIGH','complexity_state':'PROPORTIONATE','root_count_mode':'DERIVED_COMPLETE','derived_root_ids':['ROOT_H1S','ROOT_H2S'],'derived_critical_contradiction_count':0,'dominance_audit_state':'PASS'},'evidence_matrix':[{'hypothesis_id':'H1','verified_root_count':1,'decision_critical_contradictions':0,'missing_decision_critical_evidence':0,'evidence_quality':'HIGH','causal_coherence':'HIGH','notes':'load-bearing root verified'},{'hypothesis_id':'H2','verified_root_count':1,'decision_critical_contradictions':0,'missing_decision_critical_evidence':0,'evidence_quality':'HIGH','causal_coherence':'HIGH','notes':'challenger retained'}]},
 'horizon_tensor':{'version':'1.0.0','active_strategy_horizon':'SESSION_1_6H','states':[{'horizon':'SESSION_1_6H','fundamental_direction':'BULLISH','force_band':'HIGH','persistence_class':'SESSION','consumption_band':'MODERATE','remaining_asymmetry':'FAVORABLE','reversal_hazard':'MODERATE','causal_leader':'US2Y','next_update_trigger':'US2Y reversal'}],'cross_horizon_conflict_state':'ALIGNED','direction_authority':'MODULE_89_FUNDAMENTAL_HORIZON_STATE_ONLY'},
 'uncertainty_profile':{'dimensions':[{'dimension':'CAUSAL','level':'MODERATE','reason':'challenger','resolution_condition':'leader resolves'}],'decision_critical_dimensions':[],'single_confidence_score_used':False},
 'regime_state':{'as_of_utc':'2026-08-08T12:00:00Z','primary_horizon':'SESSION_1_6H','dimensions':[{'dimension':'GROWTH','state':'STABLE','evidence':[ev('REG',mat='SUPPORTING',root='ROOT_REG')],'uncertainty':'LOW','applicable_horizons':['SESSION_1_6H','DAILY_OPEN_TO_CLOSE']}],'overall_state':'COHERENT','mapping_stability':'STABLE','structural_break_risk':'LOW'},
 'causal_graph':{'graph_id':'G1','as_of_utc':'2026-08-08T12:00:00Z','horizon':'SESSION_1_6H','nodes':[{'node_id':'N1','node_type':'FACT','label':'growth fact'},{'node_id':'N2','node_type':'ASSET','label':'NASDAQ'}],'edges':[{'edge_id':'E1','from_node':'N1','to_node':'N2','edge_type':'CAUSAL','state':'ACTIVE','horizon':'SESSION_1_6H','evidence':[ev('GE',mat='SUPPORTING',root='ROOT_G')],'polarity':'POSITIVE','strength_band':'HIGH','lag_class':'SESSION','endogeneity':'EXOGENOUS','decay_state':'FRESH','activation_conditions':['growth regime stable'],'activation_predicates':[],'break_conditions':[tr('GB','growth signal breaks')]}],'root_channel_maps':[],'graph_state':'COHERENT'},
 'consumption_state':{'horizon':'SESSION_1_6H','dimensions':[{'dimension':'INFORMATION_AWARENESS','band':'MODERATE','ordinal_index':None,'evidence':['release known'],'provenance':'DIRECT'}],'lifecycle_state':'ACTIVE','remaining_asymmetry':'FAVORABLE','remaining_asymmetry_reasons':['moderate consumption'],'reopening_state':'NONE','false_precision_guard':'ORDINAL_INDICES_ARE_NOT_PROBABILITIES_OR_LITERAL_PERCENT_REMAINING'},
 'scenario_tree':{'version':'1.2.0','as_of_utc':'2026-08-08T12:00:00Z','active_horizon':'SESSION_1_6H','tree_state':'PRIMARY_SCENARIO_IDENTIFIED','scenarios':[scen('S1','BASE','H1','BULLISH','PRIMARY'),scen('S2','ADVERSE','H2','BEARISH','COMPETITIVE')],'probability_mode':'QUALITATIVE','calibration_record_id':None,'calibration_reference_class_id':None,'single_scenario_justification':None,'numeric_probabilities_used':False},
 'model_disagreement':{'disagreement_level':'LOW','unmodeled_driver_risk':'LOW','expected_signatures':['rates lead'],'observed_contradictions':[],'candidate_missing_drivers':[],'price_used_as_direction_authority':False,'action':'NONE'},
 'adversarial_review':{'builder_thesis':'growth supports','destroyer_findings':['challenger exists'],'strongest_rival_hypothesis_id':'H2','strongest_contradictory_fact':None,'same_root_double_count_risks':[],'missing_driver_candidates':[],'market_signature_contradictions':[],'post_hoc_rationalization_risk':'LOW','falsification_conditions':['US2Y reverses'],'adjudication':'THESIS_SURVIVES'},
 'premortem':{'assumed_action':'BUY','failure_paths':[{'failure_id':'F1','mechanism':'rates reversal','early_warning_trigger':tr('PF1','US2Y rises'),'monitorable':True,'monitorability_mode':'MANUAL','response':'block'}],'coverage_justification':'one load-bearing failure path in unit test','unmonitorable_decision_critical_risk':False,'unmonitorable_risk_notes':[]},
 'decision_utility':{'dimensions':[{'dimension':'UPSIDE_POTENTIAL','band':'HIGH','reason':'asymmetry'}],'utility_state':'FAVOR_ACTION','numeric_expected_utility_used':False},
 'meta_edge_router':{'primary_edge_class':'FUNDAMENTAL_EDGE','detected_edges':['FUNDAMENTAL_EDGE'],'fundamental_strategy_edge_class':'FUNDAMENTAL_EDGE','outside_strategy_edges':[],'outside_strategy_permission_effect':'NONE','research_routes':[]},
 'complexity_class':'PROPORTIONATE','load_bearing_root_ids':['ROOT_H1S','ROOT_H2S'],'non_load_bearing_context':['ROOT_REG'],'propagation_exceptions':[],'interaction_hypothesis_ids':[]}

def pack_for(x):
 facts=[]
 for h in x['hypothesis_set']['hypotheses']:
  for evr in h['supporting_evidence']:
   facts.append({'fact_id':evr['fact_id'],'primary_class':'OFFICIAL_REPORTED_FACT','availability_state':'AVAILABLE','decision_materiality':evr['materiality'],'root_cause_id':evr['root_id'],'load_bearing':True,'direction_role':'FUNDAMENTAL_ROOT','source':{'source_id':'TEST','tier':'OFFICIAL_PRIMARY'},'time':{'first_seen_time':'2026-08-08T11:00:00Z'}})
 return {'run_id':'RUN','symbol':x['instrument'],'analysis_cutoff_utc':x['analysis_cutoff_utc'],'manifest_version':'21.3.0','runtime_stack_version':'21.3.0','schema_version':'1.0.0','fact_records':facts,'coverage_receipt':{},'future_vintages_excluded':True}

m=json.loads((R/'CURRENT_PRODUCTION_MANIFEST.json').read_text());ch=m.get('cognitive_hardening') or {};ck('stack_v21_2_or_v21_3',m.get('current_stack') in {'V21.2.0','V21.3.0'},m.get('current_stack'));ck('direction_fundamental_only',m.get('decision_authority',{}).get('direction')=='FUNDAMENTAL_ONLY');ck('semantic_last_mile',ch.get('semantic_integrity_mode')=='ENFORCED_LAST_MILE')
with tempfile.TemporaryDirectory() as td0:
 td=Path(td0);ip=td/'i.json';op=td/'o.json';x=base();ip.write_text(json.dumps(x),encoding='utf-8');rc,so,se=run([T/'alphalab_cognitive_validate.py','--input',ip,'--vault-root',R]);ck('valid_pack',rc==0,so+se);rc,so,se=run([T/'alphalab_cognitive_adjudicate.py','--input',ip,'--output',op,'--vault-root',R]);z=json.loads(op.read_text());ck('clear_preserves_buy',rc==0 and z['cognitive_permission']=='BUY');ck('structured_next_review',isinstance(z.get('next_review_trigger'),dict) and z['next_review_trigger'].get('trigger_id'),z)
 def bad(name,fn):
  y=copy.deepcopy(base());fn(y);ip.write_text(json.dumps(y),encoding='utf-8');rc,so,se=run([T/'alphalab_semantic_integrity.py','--input',ip,'--vault-root',R]);ck(name,rc!=0,so+se)
 bad('directional_regime_na_blocked',lambda y:(y['cognitive_applicability'].__setitem__('regime_state',{'status':'NOT_APPLICABLE','reason':'bypass'}),y.pop('regime_state')))
 bad('root_count_mismatch',lambda y:y['hypothesis_set']['tournament_basis'].__setitem__('independent_root_count',9))
 bad('trigger_operator_missing_threshold',lambda y:y['scenario_tree']['scenarios'][0]['confirmation_triggers'].__setitem__(0,{'trigger_id':'BAD','description':'bad','monitor_mode':'MACHINE_PREDICATE','materiality':'MATERIAL','metric':'US2Y','operator':'GT'}))
 bad('premortem_auto_manual_conflict',lambda y:y['premortem']['failure_paths'][0].__setitem__('monitorability_mode','AUTOMATIC'))
 bad('broken_graph_must_propagate',lambda y:y['causal_graph'].__setitem__('graph_state','BROKEN'))
 # Explicit, auditable exception preserves flexibility.
 y=base();y['causal_graph']['graph_state']='BROKEN';y['propagation_exceptions']=[{'invariant_id':'BROKEN_CAUSAL_GRAPH_PROPAGATES','reason':'known stale diagnostic edge; not load-bearing'}];ip.write_text(json.dumps(y),encoding='utf-8');rc,so,se=run([T/'alphalab_semantic_integrity.py','--input',ip,'--vault-root',R]);ck('explicit_propagation_exception_valid',rc==0,so+se)
 # strict evidence pack reference
 y=base();pack=pack_for(y);ep=td/'pack.json';ep.write_text(json.dumps(pack));ip.write_text(json.dumps(y));rc,so,se=run([T/'alphalab_cognitive_validate.py','--input',ip,'--vault-root',R,'--evidence-pack',ep,'--require-evidence-pack']);ck('strict_d1_evidence_resolution_pass',rc==0,so+se)
 y['hypothesis_set']['hypotheses'][0]['supporting_evidence'][0]['fact_id']='FACT_DOES_NOT_EXIST';ip.write_text(json.dumps(y));rc,so,se=run([T/'alphalab_cognitive_validate.py','--input',ip,'--vault-root',R,'--evidence-pack',ep,'--require-evidence-pack']);ck('strict_d1_missing_fact_rejected',rc!=0,so+se)
 # calibrated scenario requires actual D4 ledger reference
 y=base();y['scenario_tree']['probability_mode']='CALIBRATED';y['scenario_tree']['numeric_probabilities_used']=True;y['scenario_tree']['calibration_record_id']='CAL_OK';y['scenario_tree']['calibration_reference_class_id']='RC1';y['scenario_tree']['scenarios'][0]['calibrated_probability']=.6;y['scenario_tree']['scenarios'][1]['calibrated_probability']=.4;ip.write_text(json.dumps(y));rc,so,se=run([T/'alphalab_semantic_integrity.py','--input',ip,'--vault-root',R]);ck('calibrated_without_ledger_rejected',rc!=0,so+se)
 led=td/'ledger.jsonl';led.write_text(json.dumps({'record_type':'CALIBRATION_REPORT','record_id':'CAL_OK','payload':{'record_type':'CALIBRATION_REPORT','calibration_id':'CAL_OK'}})+'\n');rc,so,se=run([T/'alphalab_semantic_integrity.py','--input',ip,'--vault-root',R,'--d4-ledger',led]);ck('calibrated_with_resolved_ledger_pass',rc==0,so+se)
 # FX policy analysis must be bilateral when material.
 y=base();y['instrument']='EURUSD';y['hypothesis_set']['instrument']='EURUSD';y['hypothesis_set']['hypotheses'][0]['family']='FX_RELATIVE_POLICY';y['cognitive_applicability']['policy_reaction_state']={'status':'PRESENT','reason':'bilateral policy material'};state={'policy_authority':'FED','as_of_utc':y['analysis_cutoff_utc'],'sensitivities':[{'variable':'INFLATION','sensitivity':'HIGH','asymmetry':'SYMMETRIC','threshold_state':'ABOVE','policy_horizon':'NEXT_MEETING','evidence_refs':[],'change_from_prior':'UNCHANGED'}],'dominant_constraints':[],'reaction_function_state':'STABLE','next_reassessment_trigger':tr('FEDREV','fed review')};y['policy_reaction_state']=state;ip.write_text(json.dumps(y));rc,so,se=run([T/'alphalab_semantic_integrity.py','--input',ip,'--vault-root',R]);ck('fx_single_policy_rejected',rc!=0,so+se)
 state2=copy.deepcopy(state);state2['policy_authority']='ECB';y['policy_reaction_state']={'mode':'BILATERAL','as_of_utc':y['analysis_cutoff_utc'],'base_currency_authority':'ECB','quote_currency_authority':'FED','states':[state2,state],'differential_state':'BALANCED','differential_reason':'unit test'};ip.write_text(json.dumps(y));rc,so,se=run([T/'alphalab_cognitive_validate.py','--input',ip,'--vault-root',R]);ck('fx_bilateral_policy_valid',rc==0,so+se)
 # telemetry retains compact deep-state summaries
 y=base();stateb=copy.deepcopy(y);stateb['cognitive_adjudication']={'applied_cognitive_constraints':[],'cognitive_rescue_candidate':False};stateb['reflexivity_state']={'aggregate_phase':'NONE'};stateb['surprise_state']={'market_surprise':'NOT_APPLICABLE','policy_implication':'NOT_APPLICABLE','asset_implication':'NOT_APPLICABLE'};stateb['driver_transition']={'state':'STABLE'};stateb['global_reconciliation']={'state':'COHERENT'};sp=td/'state.json';tp=td/'tele.json';sp.write_text(json.dumps(stateb));rc,so,se=run([T/'alphalab_cognitive_telemetry_extract.py','--state-bundle',sp,'--output',tp]);tele=json.loads(tp.read_text());ck('deep_cognitive_telemetry',rc==0 and tele.get('causal_graph_state')=='COHERENT' and tele.get('remaining_asymmetry')=='FAVORABLE' and 'OFFICIAL_PRIMARY' in tele.get('source_grade_tags',[]),tele)
err=[x for x in checks if not x['pass']];print(json.dumps({'status':'PASS' if not err else 'FAIL','tests':len(checks),'passed':len(checks)-len(err),'checks':checks},indent=2));sys.exit(0 if not err else 2)
