from __future__ import annotations
from .common import cfg,canonical_hash,stable_id,iso,parse_dt
from .maturity import maturity_for

def build_prediction(run_id,p08,p03,p07,semantic_bundle,price_anchor,cohort,event_context=None,now=None,volatility_reference=None):
    t=iso(parse_dt(now) if now else None); horizon=p08.get('horizon') or p03.get('horizon') or cfg('forward_validation_policy.json')['primary_horizon']
    anchor_ok=bool(price_anchor and isinstance(price_anchor.get('value'),(int,float)) and (price_anchor.get('source_id') or price_anchor.get('source_fact_id')))
    kh=(p07 or {}).get('kernel_health') or {}; blocked=(p07 or {}).get('analysis_admission')=='BLOCKED' or kh.get('overall_analysis_admission')=='BLOCKED'
    eligibility='BLOCKED' if not anchor_ok else ('DIAGNOSTIC_ONLY' if blocked else 'VALIDATION_ELIGIBLE')
    core={'run_id':run_id,'horizon':horizon,'precommit_time':t,'decision_hash':canonical_hash(p08),'cohort':cohort['cohort_id']}
    pred={'record_type':'AD_V3_P09_FORWARD_PREDICTION','schema_version':'1.0.0','prediction_id':stable_id('P09PRED',core),'precommit_id':stable_id('P09PRE',core),'run_id':run_id,'cohort_id':cohort['cohort_id'],'subject':'XAUUSD','horizon':horizon,'precommit_time':t,'maturity_time':maturity_for(t,horizon),'eligibility':eligibility,'sample_role':None,'causal_direction':p08.get('causal_direction','UNKNOWN'),'pressure_strength':p08.get('pressure_strength','UNKNOWN'),'dominance_state':p08.get('dominance_state','UNKNOWN'),'dominant_root':p08.get('dominant_root'),'breadth':p08.get('breadth','UNKNOWN'),'fragility':p08.get('fragility','UNKNOWN'),'persistence':next((x.get('persistence') for x in (p08.get('calibrated_roots') or []) if x.get('root_id')==p08.get('dominant_root')),'UNKNOWN'),'contradiction':p08.get('contradiction','UNKNOWN'),'consumption':p08.get('consumption','UNKNOWN'),'edge_state':p08.get('edge_state','NO_EDGE'),'permission_candidate':p08.get('permission_candidate','WAIT'),'permission_blockers':list(p08.get('blockers') or []),'missing_driver_risk':p08.get('missing_driver_risk','UNKNOWN'),'data_health':kh.get('overall_analysis_admission') or (p07 or {}).get('analysis_admission'),'semantic_health':((semantic_bundle or {}).get('p06_semantic') or {}).get('validation_status'),'semantic_mode':(semantic_bundle or {}).get('adjudication_mode'),'price_anchor':price_anchor if anchor_ok else None,'price_anchor_status':'AVAILABLE' if anchor_ok else 'UNAVAILABLE','volatility_reference':volatility_reference,'event_context':event_context or {'events':[]},'hashes':{'p03_raw':canonical_hash(p03),'p08_decision':canonical_hash(p08),'p07_kernel':canonical_hash(p07 or {}),'p06_semantic':canonical_hash(semantic_bundle or {})},'policy_versions':{'prediction':'1.0.0','episode':'1.0.0','outcome':'1.0.0','neutral_band':'1.0.0','permission_evaluation':'1.0.0'},'immutable_precommit':True,'eligibility_fixed_at_t0':True,'outcome_based_exclusion_forbidden':True,'trade_execution_authority':'NONE'}
    pred['immutable_hash']=canonical_hash(pred)
    return pred
